### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by oliversalzburg**
Very minor, I know :P More stuff coming up

### CODE REVIEW

**Comment by knownasilya** [comment]
Even small things count! :+1:

**Comment by knownasilya** [comment]
We should be using something like https://www.npmjs.com/package/debug in all the plugins

**Comment by oliversalzburg** [comment]
@knownasilya IMO there should be a *lot* more logging everywhere in strider ;D Using `debug` is probably a good choice, but it should be introduced throughout the whole project in a single sprint.

**Comment by knownasilya** [comment]
@oliversalzburg that would take a while, but we can start there, and work out to plugins.

**Comment by oliversalzburg** [comment]
@knownasilya I opened https://github.com/Strider-CD/strider/issues/794 to discuss this. Maybe we can put a checklist there for which projects got the "debug" treatment already ;)

**Pull request merged**
