### PR TITLE
Permit deploy to commits only

### PR DESCRIPTION
**Pull request by Voffkaa**
On pull requests no need to make deploy. Only for commits.

### CODE REVIEW

**Comment by knownasilya** [comment]
Hum, just wondering if this needs a config option or if this is the way it should always be. Anyone have thoughts on this?

**Comment by Voffkaa** [comment]
It would be very good to add option to select if deploy phase should be passed in dependence to job type.

**Comment by knownasilya** [comment]
Seems like it would be an option to select multiple items:

- tag
- pr
- commit
- comment
- branch
- etc..

**Comment by Voffkaa** [comment]
Unfortunately can't add frontend part now. Too long to explore Angular :)

**Comment by Voffkaa** [comment]
It would be something like 
`deploy = branch.deployOnJobType[config.trigger.type] || false`
at backend

**Comment by knownasilya** [comment]
I'll keep this open for now, and see if anyone can do the frontend portion eventually.

**Comment by Voffkaa** [comment]
Ok

**Comment by Voffkaa** [comment]
Added config option.
Frontend: https://github.com/Strider-CD/strider/pull/908

**Comment by knownasilya** [comment]
Seems like this change doesn't work because `config.trigger.type` is `'commit'` during a PR.

**Pull request merged**
