### PR TITLE
Updated Readme with more complete information on setting custom hostname and port

### PR DESCRIPTION
**Pull request by reiven**
As suggested on #34 i've attached all the needed environment variables to README file, to help new users to correctly use this plugin.

### CODE REVIEW

**Comment by knownasilya** [comment]
On thing I'm not sure about, is if `PLUGIN_GITHUB_HOSTNAME` is even used. I know it has been brought up. Could you test that, and if it's not needed, remove it from the readme.

**Comment by reiven** [comment]
You're right, @knownasilya , also "STRIDER_HOSTNAME" variables was not used.
Updated

**Comment by knownasilya** [comment]
Could you squash your commit into something logical? Otherwise looking good!

**Comment by knownasilya** [comment]
Ops, wrong button haha

**Comment by knownasilya** [comment]
Some styling issues: https://github.com/reiven/strider-github/blob/master/README.md

**Comment by reiven** [comment]
Thats weird, if you look https://github.com/reiven/strider-github that "styling" issue is not present
Anyway, i can fix it

**Comment by reiven** [comment]
Done, please check it @knownasilya

**Comment by knownasilya** [comment]
@reiven could you rebase it? Thanks!

**Comment by reiven** [comment]
Looks like there is no need. let me know if i'm wrong 
$ git rebase origin/master
Current branch master is up to date.
$ git push
Everything up-to-date

**Comment by knownasilya** [comment]
git rebase -i HEAD~[num of commits you made] e.g. `git rebase -i HEAD~3`

Then use `s` to squash everything into one commit.

**Comment by reiven** [comment]
Great , i never used before the rebase-squash things. :+1: 
Thanks!

**Comment by knownasilya** [comment]
Glad you got it working, thanks for hanging in there with me :smile:

**Pull request merged**
