### PR TITLE
Use ssh authentication instead of https

### PR DESCRIPTION
**Pull request by mandoz**
Fixes: https://github.com/Strider-CD/strider-github/issues/68

### CODE REVIEW

**Comment by knownasilya** [comment]
Just wonder if this commit affects anything else negatively..

**Comment by mandoz** [comment]
Ah the build just failed. I'll try to look into it.

**Comment by mandoz** [comment]
Seems unrelated that the build is failing. I have been manually testing and things seem fine on my end. Perhaps someone else could weigh in and tell us if that could affect something else.

**Comment by mastertinner** [comment]
@mandoz: sorry about that. the unit tests were failing even before you commited. i fixed them. can you please rebase?

**Comment by mandoz** [comment]
@mastertinner green build :)

**Comment by mudrummer012** [comment]
@mastertinner 
Any idea on when we will get a release for this?  Was wanting to user Strider as our CD tool but not being able to clone over ssh is a blocker.  Thank you @mandoz for the pull request.  Cannot wait to give this all a try.

**Comment by knownasilya** [comment]
Should be released today

**Comment by knownasilya** [comment]
Can be updated via the plugins page.

**Comment by mandoz** [comment]
If you have an existing installation of Strider-CD, you will need to do the following steps after the plugin upgrade:
1. Remove your project/repo.
2. Refresh your github repos.
3. Add the project/repo again.

This is because the value of the authentication method is set at the time the repos are fetched from github.

**Comment by knownasilya** [comment]
Looks like this change breaks normal usage of the plugin. I think we can put this behind an ENV, e.g. `STRIDER_GITHUB_USE_SSH=true`.

**Comment by knownasilya** [comment]
@mandoz does this method require the repo to have the project's ssh key to be in github?

**Pull request merged**
