### PR TITLE
Add GitHub Enterprise Support

### PR DESCRIPTION
**Pull request by apiv**
No octonode yet, wanted to get the fixes in first, so that those of us on enterprise can fully use Strider-CD.

   - [x] Tested with a github enterprise server, working
   - [x] Tested with github.com, working

### CODE REVIEW

**Comment by knownasilya** [comment]
Think it would be possible to write some tests? Or will it be too difficult?

**Comment by apiv** [comment]
I was having trouble coming up with tests to write, as I don't think there is an 'example' github enterprise server we can try to connect to. The only thing I can think of would be to ensure that the environment variables set the appConfig object in ./webapp.js.

Any ideas?

Also, it looks like my checks failed on travis, but they are passing locally. Should I try re-running?

**Comment by knownasilya** [comment]
Was thinking of setting the options, and then passing in mock data to see if it still works.

**Comment by apiv** [comment]
I'll give that a shot.

**Comment by apiv** [comment]
I haven't been able to find a way to test against different set of environment variables, short of doing some hacky things like manually invalidating the require.cache...

It may be too difficult to test around this, but the existing specs do protect the existing functionality.

**Comment by knownasilya** [comment]
I'll try to release a new version tomorrow.

**Comment by apiv** [comment]
Great, thanks!

**Pull request merged**
